compatibility_date = "2024-11-14"
compatibility_flags = ["nodejs_compat"]
name = "screenshots-manager"
pages_build_output_dir = "./dist"

r2_buckets = [
  {binding = "screenshots", bucket_name = "screenshots", remote = true}
]

[dev]
ip = "127.0.0.1"
local_protocol = "http"
port = 8788

[observability]
enabled = true
