compatibility_date = "2024-11-14"
compatibility_flags = ["nodejs_compat"]
name = "cf-worker-poc"
pages_build_output_dir = "./dist"

r2_buckets = [
  {binding = "screenshots", bucket_name = "screenshots"}
]

[dev]
ip = "127.0.0.1"
local_protocol = "http"
port = 8788
